### ISSUE TITLE
[Issue] Strange behavior when using [] at the beginning of encounter text

### ISSUE THREAD

**Issue by Filmos** [RhenaudTheLukark/CreateYourFrisk#36]
**Describe the bug**
When starting an encounter text with something (that isn't a function) between `[]`, that text is displayed before the `*` symbol.

**Code To Reproduce**
```lua
encountertext = "[abc]Hi!"
```

**Result**
![image](https://user-images.githubusercontent.com/21157064/48864958-69ddf580-edce-11e8-9ca3-12f3e6c95255.png)

**Expected behavior**
Text (with the brackets) should be displayed after the star. However, an option to add text before the star or even remove the star at all could be proven useful.

**Setup:**
 - OS: Windows
 - Version 0.6.2.1

**Comment by WD200019** [comment]
The reason this is done is to allow `[color:######]` to color the star, you see. Simply putting another command (or a letter that the font doesn't support) first can fix this, though.

These all give the same result:

```lua
encountertext = "[color:ffffff][abc"
encountertext = "[noskip][abc"
encountertext = "♪[abc"
```

![unnamed](https://user-images.githubusercontent.com/18407857/48865957-c1f90580-ed96-11e8-9c83-c39c3cee9604.png)

**Comment by WD200019** [comment]
Sorry if you saw my comment just now, I deleted it because it was wrong.

This behavior allows `[color:######]` to color the star, you see. As a temporary workaround, you can use a character not supported by the font first, and it won't be displayed, but the "not-command" will be displayed properly:

```lua
-- Examples:
encountertext = "♪[abc]"
encountertext = "ä[abc]"
encountertext = "▲[abc]"
```

But you're right, it might be a good idea to only have this exception apply to the `[color]` and/or `[alpha]` commands. We might look into it!

**Comment by RhenaudTheLukark** [comment]
Or you can also use a space! It works quite well with one
