### ISSUE TITLE
[Issue] Can't exit fullscreen (Mac)

### ISSUE THREAD

**Issue by SoshJam** [RhenaudTheLukark/CreateYourFrisk#38]
Exactly that. I pressed option+enter to get into Fullscreen, and I can't get out. It's in Fullscreen forever.

**Comment by WD200019** [comment]
What happens if you use the F4 key instead of Option+Enter?

**Comment by SoshJam** [comment]
It just toggles blurriness.

**Comment by WD200019** [comment]
Sorry, I should've worded that better.

If you turn off blurriness, use force quit (option + command + esc), kill CYF, open CYF again, and finally press F4 instead of Option+Enter, does it allow you to enter and exit fullscreen without taking over? I know that Rhenaud had an issue almost exactly like this while we were working on adding Alt+Enter support for fullscreen.

**Comment by SoshJam** [comment]
No, it doesn't. When it opens, it's in a window that takes up the whole screen, with the bottom extending below the bottom of the screen a little bit. When I press F4, it expands to fill the whole screen in blurry mode. I press it again, it goes back to 20/20 mode.

**Comment by RhenaudTheLukark** [comment]
Fixed in 0.6.2.2
