### ISSUE TITLE
Item menu doesn't open

### ISSUE THREAD

**Issue by anthony-moua** [RhenaudTheLukark/CreateYourFrisk#41]
The item menu in battles doesn't open upon selection.
1. Enter any battle.
2. Select Item option
3. Doesn't open

**Expected behavior**
The selection sound effect plays, but the item menu doesn't open.

**Setup (please complete the following information):**
 - OS: Windows
 - Version [e.g. 0.6.2.1]

**Additional context**
I opened the mods and encounters on Unitale 0.2.1a to verify that they did have items.

**Comment by WD200019** [comment]
The inventory is empty by default, this is intentional.

If you want to restore functionality from 0.2.1a (esp. for mods that used the default items, like Alphys NEO), add this code to EncounterStarting (you can also find this in CYF's Documentation):

```lua
Inventory.AddCustomItems({"Dogtest1", "Dogtest2", "Dogtest3", "Dogtest4", "Dogtest5", "Dogtest6", "Dogtest7"}, {3, 3, 3, 3, 3, 3, 3})
Inventory.SetInventory({"Dogtest1", "Dogtest2", "Dogtest3", "Dogtest4", "Dogtest5", "Dogtest6", "Dogtest7"})
```



Something of note: we do have a commit staged and ready for CYF v0.6.2.2 that adds the default "DOGTEST" items to the inventory, exactly the same as in Unitale, if you run in retrocompatibility mode. Until then, just follow the above solution.
