### ISSUE TITLE
dobble dodge of the enemy

### ISSUE THREAD

**Issue by arthuro555** [RhenaudTheLukark/CreateYourFrisk#42]
**Describe the bug**
The enemy dodges nothing again.

**To Reproduce**
Play the mod normally

**Expected behavior**
When I attack the enemy he should dodge and say something. But he doges angain while speaking (or at least make the dodge animation again). And also the 4th wave is broken but that's not a bug compatibilyty mode fixed that.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - Version: 0.6.2.1
- Mod MYTALE sans (on gamejolt)

**Additional context**
It works perfectly fine on 0.6.2.0. So the bug must come from here.

**Comment by WD200019** [comment]
This is something you've implemented and coded yourself, rather than a part of the engine, so we don't really consider this an issue. It may have changed between versions slightly, yes, but I noticed you mentioned retrocompatibility mode. It's very important that CYF mods don't require retrocompatibility mode, this feature is intended for Unitale mods people want to play in CYF.

If you like, you can post on the subreddit /r/Unitale or in our Discord server (also available from the subreddit), but we're not going to help with your mod here.

**Comment by arthuro555** [comment]
ok. Sorry. Are you going to make an android version of cyf?

**Comment by arthuro555** [comment]
And yes the mod was a cyf mod and broke since last version. retrocompatibility mode fixed one of them.

**Comment by WD200019** [comment]
1. No, there will not be an android version of CYF. This is not the place to ask.
2. I'm closing this because, as I said, this is an issue with custom Lua code and not the engine. You may take this to /r/Unitale or the discord server, but there will be no more discussion here.
