### ISSUE TITLE
Triggering an error in EndingWave() displays an unknown script

### ISSUE THREAD

**Issue by RhenaudTheLukark** [RhenaudTheLukark/CreateYourFrisk#60]
Seen on v0.6.3
I posted this so I can fix it later

**Comment by WD200019** [comment]
Testing confirms this does happen in v0.6.3 with this code:

```lua
function Update() end
function EndingWave()
    error("h")
end
```

Resulting in the output of:
```
error in script ???

chunk_2:(4,9-14): h
```

***

However, testing this in the current version of the feature branch yields this message:
```
error in script test

test:(4,9-14): h
```
(with `test` being the name of my wave script)

This was most likely fixed by these commits in order:

* https://github.com/RhenaudTheLukark/CreateYourFrisk/commit/0d69b22c6b4a4eec60902f9af86315f68ed37094
* https://github.com/RhenaudTheLukark/CreateYourFrisk/commit/b7ad690efc391ab437a2121778891b1b52bc6e69
* https://github.com/RhenaudTheLukark/CreateYourFrisk/commit/cc9cfed8ce3eeff8679f2c9d59d0ba0b1162f364
* https://github.com/RhenaudTheLukark/CreateYourFrisk/commit/6825f7e3bcd40b4693861cf2ccbf770870cc7945
* https://github.com/RhenaudTheLukark/CreateYourFrisk/commit/3ce220fc0b89a40b740cc51ef74f294cf47d4e13
* https://github.com/RhenaudTheLukark/CreateYourFrisk/commit/a97db35def719e2a4a8de9055272fde9bb5c4c23
